version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./app:/var/www/app
      - gems:/usr/local/bundle
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.2-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6.2.3-alpine
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - 8080:80
volumes:
  gems:
  database:
