Layout/EndOfLine:
  EnforcedStyle: lf
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 200